### ISSUE TITLE
Rename style prop in button to something else

### ISSUE THREAD

**Issue by xeoneux** [HHogg/preshape#1]
There's no way to add additional styles to a button by passing in style object as that prop is used for `fill` or `outline`. Please rename it to something else.

Example:
```jsx
<Button style={{background: 'red'}}>
```
won't work

**Comment by HHogg** [comment]
I guess my original thought in using the prop `style` was that inline styling will never be needed as the  API of the component should express all the possible styles of the design system. 

However, I've done a big update and changed it to simply use the boolean prop of `fill` (so default button style is outline).
